<a href="https://colab.research.google.com/github/nithin24011/Nithin_INFO5731_Spring2020/blob/main/In_class_exercise_05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## The fifth In-class-exercise (2/23/2021, 20 points in total)

In exercise-03, I asked you to collected 500 textual data based on your own information needs (If you didn't collect the textual data, you should recollect for this exercise). Now we need to think about how to represent the textual data for text classification. In this exercise, you are required to select 10 types of features (10 types of features but absolutely more than 10 features) in the followings feature list, then represent the 500 texts with these features. The output should be in the following format:
![image.png](attachment:image.png)

The feature list:

* (1) tf-idf features
* (2) POS-tag features: number of adjective, adverb, auxiliary, punctuation, complementizer, coordinating conjunction, subordinating conjunction, determiner, interjection, noun, possessor, preposition, pronoun, quantifier, verb, and other. (select some of them if you use pos-tag features)
* (3) Linguistic features:
  * number of right-branching nodes across all constituent types
  * number of right-branching nodes for NPs only
  * number of left-branching nodes across all constituent types
  * number of left-branching nodes for NPs only
  * number of premodifiers across all constituent types
  * number of premodifiers within NPs only
  * number of postmodifiers across all constituent types
  * number of postmodifiers within NPs only
  * branching index across all constituent types, i.e. the number of right-branching nodes minus number of left-branching nodes
  * branching index for NPs only
  * branching weight index: number of tokens covered by right-branching nodes minus number of tokens covered by left-branching nodes across all categories
  * branching weight index for NPs only 
  * modification index, i.e. the number of premodifiers minus the number of postmodifiers across all categories
  * modification index for NPs only
  * modification weight index: length in tokens of all premodifiers minus length in tokens of all postmodifiers across all categories
  * modification weight index for NPs only
  * coordination balance, i.e. the maximal length difference in coordinated constituents
  
  * density (density can be calculated using the ratio of folowing function words to content words) of determiners/quantifiers
  * density of pronouns
  * density of prepositions
  * density of punctuation marks, specifically commas and semicolons
  * density of auxiliary verbs
  * density of conjunctions
  * density of different pronoun types: Wh, 1st, 2nd, and 3rd person pronouns
  
  * maximal and average NP length
  * maximal and average AJP length
  * maximal and average PP length
  * maximal and average AVP length
  * sentence length

* Other features in your mind (ie., pre-defined patterns)

In [1]:
import requests
URL="http://www.values.com/inspirational-quotes"
response=requests.get(URL)

In [2]:
import requests 
from bs4 import BeautifulSoup 
  
URL = "http://www.values.com/inspirational-quotes"
r = requests.get(URL) 
  
soup = BeautifulSoup(r.content, 'html5lib') # If this line causes an error, run 'pip install html5lib' or install html5lib 

In [3]:
import requests
from bs4 import BeautifulSoup
import csv
URL = "http://www.values.com/inspirational-quotes"
r = requests.get(URL) 
   
soup = BeautifulSoup(r.content, 'html5lib') 
   
quotes=[]  # a list to store quotes 
   
table = soup.find('div', attrs = {'id':'all_quotes'})  
   
for row in table.findAll('div', 
                         attrs = {'class':'col-6 col-lg-3 text-center margin-30px-bottom sm-margin-30px-top'}): 
    quote = {} 
    quote['theme'] = row.h5.text 
    quote['url'] = row.a['href'] 
    quote['img'] = row.img['src'] 
    quote['lines'] = row.img['alt'].split(" #")[0] 
    quote['author'] = row.img['alt'].split(" #")[1] 
    quotes.append(quote) 
   
filename = 'inspirational_quotes.csv'
with open(filename, 'w', newline='') as f: 
    w = csv.DictWriter(f,['theme','url','img','lines','author']) 
    w.writeheader() 
    for quote in quotes: 
        w.writerow(quote)

In [4]:
import pandas as pd
csvfile=pd.read_csv('inspirational_quotes.csv')
print(csvfile)

          theme  ...                       author
0    FRIENDSHIP  ...  <Author:0x00007f252cbe1ec0>
1    FRIENDSHIP  ...  <Author:0x00007f252cc0a870>
2    FRIENDSHIP  ...  <Author:0x00007f252cc213b8>
3    FRIENDSHIP  ...  <Author:0x00007f252cc4b410>
4    FRIENDSHIP  ...  <Author:0x00007f252cc69d98>
5     LIVE LIFE  ...  <Author:0x00007f252cc88388>
6     LIVE LIFE  ...  <Author:0x00007f252ccac198>
7     LIVE LIFE  ...  <Author:0x00007f252ccd9b70>
8     LIVE LIFE  ...  <Author:0x00007f252cd0b148>
9     LIVE LIFE  ...  <Author:0x00007f252cd200c0>
10         LOVE  ...  <Author:0x00007f252cd49128>
11         LOVE  ...  <Author:0x00007f252cd74a58>
12         LOVE  ...  <Author:0x00007f252cd9d840>
13         LOVE  ...  <Author:0x00007f252cdc6d80>
14         LOVE  ...  <Author:0x00007f252cdf4848>
15   CONFIDENCE  ...  <Author:0x00007f252ce18310>
16   CONFIDENCE  ...  <Author:0x00007f252ce57308>
17   CONFIDENCE  ...  <Author:0x00007f252ce976b0>
18   CONFIDENCE  ...  <Author:0x00007f252ceaabc0>


In [5]:
dat = pd.read_csv('inspirational_quotes.csv')
print(dat.shape)
dat.head(5)

(32, 5)


theme  ...                       author
0  FRIENDSHIP  ...  <Author:0x00007f252cbe1ec0>
1  FRIENDSHIP  ...  <Author:0x00007f252cc0a870>
2  FRIENDSHIP  ...  <Author:0x00007f252cc213b8>
3  FRIENDSHIP  ...  <Author:0x00007f252cc4b410>
4  FRIENDSHIP  ...  <Author:0x00007f252cc69d98>

[5 rows x 5 columns]

In [6]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()
# tokenize and build vocab
vectorizer.fit(dat)
# summarize
print(vectorizer.vocabulary_)
# encode document
vector = vectorizer.transform(dat)
# summarize encoded vector
print(vector.toarray())

{'theme': 3, 'url': 4, 'img': 1, 'lines': 2, 'author': 0}
[[0 0 0 1 0]
 [0 0 0 0 1]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [1 0 0 0 0]]


In [7]:
from sklearn.feature_extraction.text import TfidfVectorizer

# create the transform
vectorizer = TfidfVectorizer()
# tokenize and build vocab
vectorizer.fit(dat)
# summarize
print(vectorizer.vocabulary_)
print(vectorizer.idf_)
# encode document
vector = vectorizer.transform(dat)
# summarize encoded vector

print(vector.toarray())

{'theme': 3, 'url': 4, 'img': 1, 'lines': 2, 'author': 0}
[2.09861229 2.09861229 2.09861229 2.09861229 2.09861229]
[[0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]]


In [8]:
from sklearn.feature_extraction.text import HashingVectorizer

vectorizer = HashingVectorizer(n_features=50)
# encode document
vector = vectorizer.transform(dat)
# summarize encoded vector
print(vector.shape)
print(vector.toarray())

(5, 50)
[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. -1.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0

In [9]:
file = open("inspirational_quotes.csv")
reader = csv.reader(file)

data = [
    [(word.replace(",", "")
          .replace(".", "")
          .replace("(", "")
          .replace(")", ""))
    for word in row[2].lower().split()]
    for row in reader]

#Removes header
data = data[1:]

In [10]:
from sklearn.feature_extraction.text import TfidfVectorizer
v = TfidfVectorizer()
x = v.fit_transform(dat)#['author'])
x.toarray()


array([[0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0.]])

In [11]:
!pip install texthero


In [12]:
import texthero as hero
dat['tfidf'] = hero.tfidf(dat['author'])
dat['tfidf1'] = hero.tfidf(dat['lines'])

In [13]:
dat.head(35)


theme  ...                                             tfidf1
0    FRIENDSHIP  ...  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
1    FRIENDSHIP  ...  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
2    FRIENDSHIP  ...  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
3    FRIENDSHIP  ...  [0.0, 0.3357234446007204, 0.0, 0.0, 0.0, 0.0, ...
4    FRIENDSHIP  ...  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
5     LIVE LIFE  ...  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
6     LIVE LIFE  ...  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.28215623...
7     LIVE LIFE  ...  [0.13105213901839854, 0.0, 0.0, 0.0, 0.0, 0.0,...
8     LIVE LIFE  ...  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
9     LIVE LIFE  ...  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.2776508270613...
10         LOVE  ...  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
11         LOVE  ...  [0.18396596525438177, 0.0, 0.0, 0.0, 0.0, 0.0,...
12         LOVE  ...  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
13         LOVE  ...  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
14         LOVE  ...  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
15   CONFIDENCE  ...  [0.0, 0.0, 0.0, 0.0, 0.2654315866231416, 0.0, ...
16   CONFIDENCE  ...  [0.0, 0.0, 0.3348373012146534, 0.0, 0.0, 0.0, ...
17   CONFIDENCE  ...  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
18   CONFIDENCE  ...  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
19   CONFIDENCE  ...  [0.0, 0.0, 0.0, 0.7556164153132985, 0.0, 0.0, ...
20      BRAVERY  ...  [0.0, 0.0, 0.0, 0.0, 0.0, 0.20378884834590905,...
21      BRAVERY  ...  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
22      BRAVERY  ...  [0.0, 0.0, 0.0, 0.0, 0.0, 0.2189210575323713, ...
23      BRAVERY  ...  [0.0, 0.0, 0.0, 0.332901159857354, 0.0, 0.0, 0...
24      BRAVERY  ...  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
25  PREPARATION  ...  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
26  PREPARATION  ...  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
27  PREPARATION  ...  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
28  PREPARATION  ...  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.276...
29  PREPARATION  ...  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
30    CHARACTER  ...  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
31    CHARACTER  ...  [0.0, 0.0, 0.18469617979541736, 0.0, 0.0, 0.0,...

[32 rows x 7 columns]

In [15]:

tf1 = (dat['author'][0:31]).apply(lambda x: pd.value_counts(x.split(" "))).sum(axis = 0).reset_index()
tf1.columns = ['words','tf']

In [16]:
import numpy as np
for i,word in enumerate(tf1['words']):
  tf1.loc[i, 'idf'] = np.log(dat.shape[0]/(len(dat[dat['author'].str.contains(word)])))

tf1

words   tf       idf
0   <Author:0x00007f252cbe1ec0>  1.0  3.465736
1   <Author:0x00007f252cc0a870>  1.0  3.465736
2   <Author:0x00007f252cc213b8>  1.0  3.465736
3   <Author:0x00007f252cc4b410>  1.0  3.465736
4   <Author:0x00007f252cc69d98>  1.0  3.465736
5   <Author:0x00007f252cc88388>  1.0  3.465736
6   <Author:0x00007f252ccac198>  1.0  3.465736
7   <Author:0x00007f252ccd9b70>  1.0  3.465736
8   <Author:0x00007f252cd0b148>  1.0  3.465736
9   <Author:0x00007f252cd200c0>  1.0  3.465736
10  <Author:0x00007f252cd49128>  1.0  3.465736
11  <Author:0x00007f252cd74a58>  1.0  3.465736
12  <Author:0x00007f252cd9d840>  1.0  3.465736
13  <Author:0x00007f252cdc6d80>  1.0  3.465736
14  <Author:0x00007f252cdf4848>  1.0  3.465736
15  <Author:0x00007f252ce18310>  1.0  3.465736
16  <Author:0x00007f252ce57308>  1.0  3.465736
17  <Author:0x00007f252ce976b0>  1.0  3.465736
18  <Author:0x00007f252ceaabc0>  1.0  3.465736
19  <Author:0x00007f252cf0fd18>  1.0  3.465736
20  <Author:0x00007f252cf1ec50>  1.0  3.465736
21  <Author:0x00007f252cf3db50>  1.0  3.465736
22  <Author:0x00007f252cf61320>  1.0  3.465736
23  <Author:0x00007f252cf9ac10>  1.0  3.465736
24  <Author:0x00007f252cfcfca8>  1.0  3.465736
25  <Author:0x00007f252d007158>  1.0  3.465736
26  <Author:0x00007f252d028498>  1.0  3.465736
27  <Author:0x00007f252d055c18>  1.0  3.465736
28  <Author:0x00007f252d079348>  1.0  3.465736
29  <Author:0x00007f252d0a6488>  1.0  3.465736
30  <Author:0x00007f252d0d2358>  1.0  3.465736

In [17]:
import nltk
nltk.download('averaged_perceptron_tagger')
from nltk.tokenize import word_tokenize
nltk.download('punkt')
try1=[]
for i in dat['author']:
  text = word_tokenize(i)
  try1.append(nltk.pos_tag(text))

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


In [18]:
c_nn=0
c_vb=0

for i in try1:
  for j,k in i:
    
    if k=="NN":
      c_nn+=1
    if k=="JJ":
      c_vb+=1

c_nn

32

In [19]:
import spacy
nlp=spacy.load("en_core_web_sm")
for i in dat['author']:
  for token in nlp(i):
    print(token.text,"=>",token.pos_,"=>",token.tag_)

< => X => XX
Author:0x00007f252cbe1ec0 => PROPN => NNP
> => X => XX
< => X => XX
Author:0x00007f252cc0a870 => PROPN => NNP
> => X => XX
< => X => XX
Author:0x00007f252cc213b8 => PROPN => NNP
> => X => XX
< => X => XX
Author:0x00007f252cc4b410 => ADV => RB
> => X => XX
< => X => XX
Author:0x00007f252cc69d98 => PROPN => NNP
> => X => XX
< => X => XX
Author:0x00007f252cc88388 => PROPN => NNP
> => X => XX
< => X => XX
Author:0x00007f252ccac198 => PROPN => NNP
> => X => XX
< => X => XX
Author:0x00007f252ccd9b70 => PROPN => NNP
> => X => XX
< => X => XX
Author:0x00007f252cd0b148 => PROPN => NNP
> => X => XX
< => X => XX
Author:0x00007f252cd200c0 => PROPN => NNP
> => X => XX
< => X => XX
Author:0x00007f252cd49128 => PROPN => NNP
> => X => XX
< => X => XX
Author:0x00007f252cd74a58 => PROPN => NNP
> => X => XX
< => X => XX
Author:0x00007f252cd9d840 => PUNCT => :
> => X => XX
< => X => XX
Author:0x00007f252cdc6d80 => PROPN => NNP
> => X => XX
< => X => XX
Author:0x00007f252cdf4848 => PROPN => NN

In [20]:
import spacy
nlp=spacy.load("en_core_web_sm")
for i in dat['lines']:
  for token in nlp(i):
    print(token.text,"=>",token.pos_,"=>",token.tag_)

Friendship => NOUN => NN
is => AUX => VBZ
a => DET => DT
strong => ADJ => JJ
and => CCONJ => CC
habitual => ADJ => JJ
inclination => NOUN => NN
in => ADP => IN
two => NUM => CD
persons => NOUN => NNS
to => PART => TO
promote => VERB => VB
the => DET => DT
good => NOUN => NN
and => CCONJ => CC
happiness => NOUN => NN
of => ADP => IN
one => NOUN => NN
another => DET => DT
. => PUNCT => .
The => DET => DT
most => ADV => RBS
beautiful => ADJ => JJ
discovery => NOUN => NN
true => ADJ => JJ
friends => NOUN => NNS
make => VERB => VBP
is => AUX => VBZ
that => SCONJ => IN
they => PRON => PRP
can => VERB => MD
grow => VERB => VB
separately => ADV => RB
without => ADP => IN
growing => VERB => VBG
apart => ADV => RB
. => PUNCT => .
Friends => NOUN => NNS
are => AUX => VBP
the => DET => DT
family => NOUN => NN
you => PRON => PRP
choose => VERB => VBP
. => PUNCT => .
Anything => PRON => NN
is => AUX => VBZ
possible => ADJ => JJ
when => ADV => WRB
you => PRON => PRP
have => AUX => VBP
the => DET => D